name: release

on:
  - workflow_dispatch

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: npm
          registry-url: 'https://registry.npmjs.org'

      - name: Configure git user
        run: |
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config user.name "github-actions[bot]"

      - run: npm ci
      - run: npm run build

      - name: Publish site
        run: |
          set -x

          mv ./build /tmp/build

          git reset HEAD --hard
          git fetch origin site:site
          git checkout site
          git rm -rf --ignore-unmatch .
          git clean -fxd

          cp -R /tmp/build/. .

          git add .

          ! git diff --staged --quiet --exit-code || exit 0

          git commit -m "Updated site (${GITHUB_SHA::7})"
          git push origin site
